/* Generated by bin2c, do not edit manually */
#ifndef __startup_sound_h_included
#define __startup_sound_h_included

/* Contents of file noice.raw */
extern const long int sound_raw_size;
extern const unsigned char sound_raw[90422];

#endif    /* __startup_sound_h_included */
