/* Generated by bin2c, do not edit manually */
#ifndef __startup_sound_h_included
#define __startup_sound_h_included

#include "stm32h7xx_hal.h"

const uint32_t noice_raw_size;
const uint16_t noice_raw[90422];

#endif    /* __startup_sound_h_included */
